routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome')->name('welcome')->middleware('guest');

Auth::routes();

// Change Password Routes
Route::get('change-password', 'Auth\ChangePasswordController@show');
Route::patch('change-password', 'Auth\ChangePasswordController@update')->name('password.change');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'TransactionsController@index')->name('home');

    /*
     * User Profile Routes
     */
    Route::get('profile', 'Auth\ProfileController@show')->name('profile.show');
    Route::get('profile/edit', 'Auth\ProfileController@edit')->name('profile.edit');
    Route::patch('profile/update', 'Auth\ProfileController@update')->name('profile.update');

    /*
     * Transactions Routes
     */
    Route::get('transaction_search', 'TransactionSearchController@index')->name('transaction_search.index');
    Route::get('transactions/export-csv', 'Transactions\ExportController@csv')->name('transactions.exports.csv');
    Route::resource('transactions', 'TransactionsController');

    /*
     * Categories Routes
     */
    Route::get('categories/{category}/export-csv', 'Transactions\ExportController@byCategory')->name('transactions.exports.by_category');
    Route::resource('categories', 'CategoriesController');

    /*
     * Loans Routes
     */
    Route::resource('loans', 'LoanController');
    Route::post('loans/{loan}/transactions', 'Loans\TransactionController@store')
        ->name('loans.transactions.store');

    /*
     * Report Routes
     */
    Route::get('/report', 'ReportsController@index')->name('reports.index');

    /*
     * Partners Routes
     */
    Route::get('partners/{partner}/export-csv', 'Transactions\ExportController@byPartner')->name('transactions.exports.by_partner');
    Route::resource('partners', 'PartnerController');

    /*
     * Lang switcher routes
     */
    Route::patch('lang_switch', 'LangSwitcherController@update')->name('lang.switch');
});

app/Loan.php
<?php

namespace App;

use App\Traits\Models\ForUser;
use Illuminate\Database\Eloquent\Model;

class Loan extends Model
{
    use ForUser;

    const TYPE_DEBT = 1;
    const TYPE_RECEIVABLE = 2;

    protected $fillable = [
        'partner_id', 'type_id', 'amount', 'description', 'creator_id',
        'start_date', 'end_date', 'planned_payment_count',
    ];

    public function creator()
    {
        return $this->belongsTo(User::class);
    }

    public function partner()
    {
        return $this->belongsTo(Partner::class);
    }

    public function getTypeAttribute()
    {
        if ($this->type_id == Loan::TYPE_DEBT) {
            return __('loan.types.debt');
        }

        return __('loan.types.receivable');
    }

    public function getAmountStringAttribute()
    {
        return number_format($this->amount, 2);
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }

    public function getPaymentTotalAttribute()
    {
        $paymentType = $this->type_id == static::TYPE_DEBT ? 0 : 1;

        return $this->transactions()->where('in_out', $paymentType)->sum('amount');
    }

    public function getPaymentTotalStringAttribute()
    {
        return number_format($this->payment_total, 2);
    }

    public function getPaymentRemainingAttribute()
    {
        return $this->amount - $this->payment_total;
    }

    public function getPaymentRemainingStringAttribute()
    {
        return number_format($this->payment_remaining, 2);
    }

    public function getTypeLabelAttribute()
    {
        $bgColor = $this->type_id == static::TYPE_DEBT ? '#00aabb' : '#bb004f';
        $type = $this->type;
        if ($this->end_date) {
            $type .= ' <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>';
        }

        return '<span class="badge" style="background-color: '.$bgColor.'">'.$type.'</span>';
    }

    public function delete()
    {
        $this->transactions()->update(['loan_id' => null]);

        return parent::delete();
    }
}

app/Partner.php
<?php

namespace App;

use App\Traits\Models\ConstantsGetter;
use App\Traits\Models\ForUser;
use Illuminate\Database\Eloquent\Model;

class Partner extends Model
{
    use ForUser, ConstantsGetter;

    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 1;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'description', 'status_id', 'creator_id'];

    /**
     * Partner belongs to user creator relation.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function creator()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Partner has many transactions relation.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }

    /**
     * Get partner name label attribute.
     *
     * @return string
     */
    public function getNameLabelAttribute()
    {
        return '<span class="badge badge-pill badge-secondary">'.$this->name.'</span>';
    }

    public function getStatusAttribute()
    {
        return $this->status_id == static::STATUS_INACTIVE ? __('app.inactive') : __('app.active');
    }
}

app/Http/Controllers/TransactionSearchController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use Illuminate\Http\Request;

class TransactionSearchController extends Controller
{
    public function index(Request $request)
    {
        $defaultStartDate = auth()->user()->account_start_date ?: date('Y-m').'-01';
        $startDate = request('start_date', $defaultStartDate);
        $endDate = request('end_date', date('Y-m-t'));

        $transactions = collect([]);
        $searchQuery = $request->get('search_query');
        $categoryId = $request->get('category_id');
        $partnerId = $request->get('partner_id');
        if ($searchQuery) {
            $transactionQuery = Transaction::orderBy('date', 'desc');
            $transactionQuery->whereBetween('date', [$startDate, $endDate]);
            if ($searchQuery != '---') {
                $transactionQuery->where('description', 'like', '%'.$searchQuery.'%');
            }
            if ($categoryId) {
                $transactionQuery->where('category_id', $categoryId);
            }
            if ($partnerId) {
                $transactionQuery->where('partner_id', $partnerId);
            }
            $transactions = $transactionQuery->with('category', 'partner', 'loan')->limit(100)->get();
        }
        $partners = $this->getPartnerList();
        $categories = $this->getCategoryList();

        return view('transaction_search.index', compact(
            'searchQuery', 'transactions', 'startDate', 'endDate', 'partners', 'categories'
        ));
    }
}

resources/views/transaction_search/index.blade.php
@extends('layouts.app')

@section('title', __('transaction.search'))

@section('content')

<div class="page-header">
    <h1 class="page-title">{{ __('transaction.search') }}</h1>
    <div class="page-subtitle">{{ $transactions->count() }} {{ __('transaction.transaction') }}</div>
    <div class="page-options d-flex">
        {{ link_to_route('transactions.index', __('transaction.back_to_index'), [], ['class' => 'btn btn-secondary float-right']) }}
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card table-responsive">
            <div class="card-header">
                {{ Form::open(['method' => 'get', 'class' => 'form-inline']) }}
                    {{ Form::text('search_query', request('search_query'), ['class' => 'form-control form-control-sm mr-2 mt-4 mt-sm-0', 'placeholder' => __('transaction.search_text')]) }}
                    {{ Form::text('start_date', $startDate, ['class' => 'form-control form-control-sm mr-2 mt-4 mt-sm-0 date-select', 'style' => 'width:100px', 'placeholder' => __('time.start_date')]) }}
                    {{ Form::text('end_date', $endDate, ['class' => 'form-control form-control-sm mr-2 mt-4 mt-sm-0 date-select', 'style' => 'width:100px', 'placeholder' => __('time.end_date')]) }}
                    {{ Form::select('category_id', $categories, request('category_id'), ['placeholder' => __('category.all'), 'class' => 'form-control form-control-sm mr-2 mt-4 mt-sm-0', ]) }}
                    {{ Form::select('partner_id', $partners, request('partner_id'), ['placeholder' => __('partner.all'), 'class' => 'form-control form-control-sm mr-2 mt-4 mt-sm-0', ]) }}
                    <div class="form-group mt-4 mt-sm-0">
                        {{ Form::submit(__('app.search'), ['class' => 'btn btn-primary btn-sm mr-2']) }}
                        {{ link_to_route('transaction_search.index', __('app.reset'), [], ['class' => 'btn btn-secondary btn-sm']) }}
                    </div>
                {{ Form::close() }}
            </div>
            @if ($searchQuery)
                @desktop
                <table class="table table-sm table-responsive-sm table-hover table-bordered mb-0">
                    <thead>
                        <tr>
                            <th class="text-center col-md-1">{{ __('app.table_no') }}</th>
                            <th class="text-center col-md-2">{{ __('app.date') }}</th>
                            <th class="col-md-7">{{ __('transaction.description') }}</th>
                            <th class="text-right col-md-2">{{ __('transaction.amount') }}</th>
                            <th class="text-center">{{ __('app.action') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($transactions as $key => $transaction)
                        <tr>
                            <td class="text-center">{{ 1 + $key }}</td>
                            <td class="text-center">{{ $transaction->date }}</td>
                            <td>
                                {{ $transaction->description }}
                                <div class="float-right">
                                    @if ($transaction->loan)
                                        @php
                                            $loanRoute = route('loans.show', $transaction->loan);
                                        @endphp
                                        <a href="{{ $loanRoute }}">{!! $transaction->loan->type_label !!}</a>
                                    @endif
                                    @if ($transaction->partner)
                                        @php
                                            $partnerRoute = route('partners.show', [
                                                $transaction->partner_id,
                                                'start_date' => $startDate,
                                                'end_date' => $endDate,
                                            ]);
                                        @endphp
                                        <a href="{{ $partnerRoute }}">{!! $transaction->partner->name_label !!}</a>
                                    @endif
                                    @if ($transaction->category)
                                        @php
                                            $categoryRoute = route('categories.show', [
                                                $transaction->category_id,
                                                'start_date' => $startDate,
                                                'end_date' => $endDate,
                                            ]);
                                        @endphp
                                        <a href="{{ $categoryRoute }}">{!! $transaction->category->name_label !!}</a>
                                    @endif
                                </div>
                            </td>
                            <td class="text-right">{{ $transaction->amount_string }}</td>
                            <td class="text-center text-nowrap">
                                {{ link_to_route('transactions.index', __('app.show'), [
                                    'query' => $searchQuery,
                                    'date' => $transaction->date_only,
                                    'month' => $transaction->month,
                                    'year' => $transaction->year,
                                ], ['class' => 'btn btn-secondary btn-sm']) }}
                            </td>
                        </tr>
                        @empty
                        <tr><td colspan="5">{{ __('transaction.not_found') }}</td></tr>
                        @endforelse
                    </tbody>
                </table>
                @elsedesktop
                <div class="card-body">
                    @foreach ($transactions as $transaction)
                        @include('transaction_search.partials.single_transaction_mobile', ['transaction' => $transaction])
                    @endforeach
                </div>
                @enddesktop
            @endif
        </div>
    </div>
</div>
@endsection

@section('styles')
    {{ Html::style(url('css/plugins/jquery.datetimepicker.css')) }}
@endsection

@push('scripts')
    {{ Html::script(url('js/plugins/jquery.datetimepicker.js')) }}
<script>
(function () {
    $('.date-select').datetimepicker({
        timepicker:false,
        format:'Y-m-d',
        closeOnDateSelect: true,
        scrollInput: false,
        dayOfWeekStart: 1
    });
})();
</script>
@endpush