routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome')->name('welcome')->middleware('guest');

Auth::routes();

// Change Password Routes
Route::get('change-password', 'Auth\ChangePasswordController@show');
Route::patch('change-password', 'Auth\ChangePasswordController@update')->name('password.change');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'TransactionsController@index')->name('home');

    /*
     * User Profile Routes
     */
    Route::get('profile', 'Auth\ProfileController@show')->name('profile.show');
    Route::get('profile/edit', 'Auth\ProfileController@edit')->name('profile.edit');
    Route::patch('profile/update', 'Auth\ProfileController@update')->name('profile.update');

    /*
     * Transactions Routes
     */
    Route::get('transaction_search', 'TransactionSearchController@index')->name('transaction_search.index');
    Route::get('transactions/export-csv', 'Transactions\ExportController@csv')->name('transactions.exports.csv');
    Route::resource('transactions', 'TransactionsController');

    /*
     * Categories Routes
     */
    Route::get('categories/{category}/export-csv', 'Transactions\ExportController@byCategory')->name('transactions.exports.by_category');
    Route::resource('categories', 'CategoriesController');

    /*
     * Loans Routes
     */
    Route::resource('loans', 'LoanController');
    Route::post('loans/{loan}/transactions', 'Loans\TransactionController@store')
        ->name('loans.transactions.store');

    /*
     * Report Routes
     */
    Route::get('/report', 'ReportsController@index')->name('reports.index');

    /*
     * Partners Routes
     */
    Route::get('partners/{partner}/export-csv', 'Transactions\ExportController@byPartner')->name('transactions.exports.by_partner');
    Route::resource('partners', 'PartnerController');

    /*
     * Lang switcher routes
     */
    Route::patch('lang_switch', 'LangSwitcherController@update')->name('lang.switch');
});

app/Loan.php
<?php

namespace App;

use App\Traits\Models\ForUser;
use Illuminate\Database\Eloquent\Model;

class Loan extends Model
{
    use ForUser;

    const TYPE_DEBT = 1;
    const TYPE_RECEIVABLE = 2;

    protected $fillable = [
        'partner_id', 'type_id', 'amount', 'description', 'creator_id',
        'start_date', 'end_date', 'planned_payment_count',
    ];

    public function creator()
    {
        return $this->belongsTo(User::class);
    }

    public function partner()
    {
        return $this->belongsTo(Partner::class);
    }

    public function getTypeAttribute()
    {
        if ($this->type_id == Loan::TYPE_DEBT) {
            return __('loan.types.debt');
        }

        return __('loan.types.receivable');
    }

    public function getAmountStringAttribute()
    {
        return number_format($this->amount, 2);
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }

    public function getPaymentTotalAttribute()
    {
        $paymentType = $this->type_id == static::TYPE_DEBT ? 0 : 1;

        return $this->transactions()->where('in_out', $paymentType)->sum('amount');
    }

    public function getPaymentTotalStringAttribute()
    {
        return number_format($this->payment_total, 2);
    }

    public function getPaymentRemainingAttribute()
    {
        return $this->amount - $this->payment_total;
    }

    public function getPaymentRemainingStringAttribute()
    {
        return number_format($this->payment_remaining, 2);
    }

    public function getTypeLabelAttribute()
    {
        $bgColor = $this->type_id == static::TYPE_DEBT ? '#00aabb' : '#bb004f';
        $type = $this->type;
        if ($this->end_date) {
            $type .= ' <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>';
        }

        return '<span class="badge" style="background-color: '.$bgColor.'">'.$type.'</span>';
    }

    public function delete()
    {
        $this->transactions()->update(['loan_id' => null]);

        return parent::delete();
    }
}

app/Http/Controllers/LoanController.php
<?php

namespace App\Http\Controllers;

use App\Loan;
use App\Transaction;
use Illuminate\Http\Request;

class LoanController extends Controller
{
    /**
     * Display a listing of the loan.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $loanQuery = Loan::query();
        if ($request->get('q')) {
            $loanQuery->where('description', 'like', '%'.$request->get('q').'%');
        }
        if ($request->get('type_id')) {
            $loanQuery->where('type_id', 'like', '%'.$request->get('type_id').'%');
        }
        $loans = $loanQuery->with(['partner'])->latest()->paginate(25);

        return view('loans.index', compact('loans'));
    }

    /**
     * Show the form for creating a new loan.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $this->authorize('create', new Loan);
        $partners = $this->getPartnerList();
        $loanTypes = [
            Loan::TYPE_DEBT       => __('loan.types.debt'),
            Loan::TYPE_RECEIVABLE => __('loan.types.receivable'),
        ];

        return view('loans.create', compact('partners', 'loanTypes'));
    }

    /**
     * Store a newly created loan in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->authorize('create', new Loan);

        $newLoan = $request->validate([
            'partner_id'            => 'required|exists:partners,id',
            'type_id'               => 'required|in:'.Loan::TYPE_DEBT.','.Loan::TYPE_RECEIVABLE,
            'amount'                => 'required|numeric',
            'planned_payment_count' => 'required|numeric',
            'description'           => 'required|max:255',
            'start_date'            => 'nullable|date_format:Y-m-d',
            'end_date'              => 'nullable|date_format:Y-m-d',
        ]);
        $newLoan['creator_id'] = auth()->id();

        $loan = Loan::create($newLoan);
        $newTransaction = [
            'loan_id'     => $loan->id,
            'in_out'      => $loan->type_id == Loan::TYPE_DEBT ? 1 : 0, // 0:spending, 1:income
            'amount'      => $loan->amount,
            'date'        => $loan->start_date ?: $loan->created_at->format('Y-m-d'),
            'description' => $loan->description,
            'partner_id'  => $loan->partner_id,
            'creator_id'  => $loan->creator_id,
        ];
        Transaction::create($newTransaction);

        return redirect()->route('loans.show', $loan);
    }

    /**
     * Display the specified loan.
     *
     * @param  \App\Loan  $loan
     * @return \Illuminate\View\View
     */
    public function show(Loan $loan)
    {
        $transactions = $loan->transactions;
        $inOutOptions = [__('loan.pay_debt'), __('loan.add_debt')];
        $defaultInOutValue = 0;
        if ($loan->type_id == Loan::TYPE_RECEIVABLE) {
            $inOutOptions = [
                1 => $loan->partner->name.' '.__('loan.pay_debt'),
                0 => $loan->partner->name.' '.__('loan.add_debt'),
            ];
            $defaultInOutValue = 1;
        }

        return view('loans.show', compact('loan', 'transactions', 'inOutOptions', 'defaultInOutValue'));
    }

    /**
     * Show the form for editing the specified loan.
     *
     * @param  \App\Loan  $loan
     * @return \Illuminate\View\View
     */
    public function edit(Loan $loan)
    {
        $this->authorize('update', $loan);
        $partners = $this->getPartnerList();
        $loanTypes = [
            Loan::TYPE_DEBT       => __('loan.types.debt'),
            Loan::TYPE_RECEIVABLE => __('loan.types.receivable'),
        ];

        return view('loans.edit', compact('loan', 'partners', 'loanTypes'));
    }

    /**
     * Update the specified loan in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Loan  $loan
     * @return \Illuminate\Routing\Redirector
     */
    public function update(Request $request, Loan $loan)
    {
        $this->authorize('update', $loan);

        $loanData = $request->validate([
            'partner_id'            => 'required|exists:partners,id',
            'type_id'               => 'required|in:'.Loan::TYPE_DEBT.','.Loan::TYPE_RECEIVABLE,
            'amount'                => 'required|numeric',
            'planned_payment_count' => 'required|numeric',
            'description'           => 'required|max:255',
            'start_date'            => 'nullable|date_format:Y-m-d',
            'end_date'              => 'nullable|date_format:Y-m-d',
        ]);
        $loan->update($loanData);
        $transaction = $loan->transactions()->orderBy('created_at')->first();
        if ($transaction) {
            $transaction->partner_id = $loan->partner_id;
            $transaction->amount = $loan->amount;
            $transaction->date = $loan->start_date;
            $transaction->description = $loan->description;
            $transaction->in_out = $loan->type_id == Loan::TYPE_DEBT ? 1 : 0; // 0:spending, 1:income
            $transaction->save();
        }

        return redirect()->route('loans.show', $loan);
    }

    /**
     * Remove the specified loan from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Loan  $loan
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy(Request $request, Loan $loan)
    {
        $this->authorize('delete', $loan);

        $request->validate(['loan_id' => 'required']);

        if ($request->get('loan_id') == $loan->id && $loan->delete()) {
            return redirect()->route('loans.index');
        }

        return back();
    }
}

app/Http/Controllers/Loans/TransactionController.php
<?php

namespace App\Http\Controllers\Loans;

use App\Events\Loans\PaymentCreated as LoanPaymentCreated;
use App\Http\Controllers\Controller;
use App\Loan;
use App\Transaction;
use Illuminate\Http\Request;

class TransactionController extends Controller
{
    public function store(Request $request, Loan $loan)
    {
        $newTransaction = $request->validate([
            'amount'      => 'required|numeric',
            'date'        => 'required|date_format:Y-m-d',
            'in_out'      => 'required|boolean',
            'description' => 'required|max:255',
        ]);
        $newTransaction['loan_id'] = $loan->id;
        $newTransaction['partner_id'] = $loan->partner_id;
        $newTransaction['creator_id'] = auth()->id();
        $transaction = Transaction::create($newTransaction);

        event(new LoanPaymentCreated($loan, $transaction));

        return redirect()->route('loans.show', $loan);
    }
}

resources/views/loans/create.blade.php
@extends('layouts.app')

@section('title', __('loan.create'))

@section('content')
<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-header"><h3 class="card-title">{{ __('loan.create') }}</h3></div>
            {{ Form::open(['route' => 'loans.store']) }}
            <div class="card-body">
                {!! FormField::select('partner_id', $partners, ['required' => true, 'label' => __('loan.partner')]) !!}
                {!! FormField::radios('type_id', $loanTypes, ['required' => true, 'label' => __('loan.type')]) !!}
                <div class="row">
                    <div class="col-md-6">
                        {!! FormField::text('amount', ['required' => true, 'type' => 'number', 'label' => __('loan.amount')]) !!}
                    </div>
                    <div class="col-md-6">
                        {!! FormField::text('planned_payment_count', ['required' => true, 'type' => 'number', 'value' => old('planned_payment_count', 1), 'label' => __('loan.planned_payment_count')]) !!}
                    </div>
                </div>
                {!! FormField::textarea('description', ['label' => __('loan.description')]) !!}
                <div class="row">
                    <div class="col-md-6">
                        {!! FormField::text('start_date', ['class' => 'date-select', 'label' => __('loan.start_date')]) !!}
                    </div>
                    <div class="col-md-6">
                        {!! FormField::text('end_date', ['class' => 'date-select', 'label' => __('loan.end_date')]) !!}
                    </div>
                </div>
            </div>
            <div class="card-footer">
                {{ Form::submit(__('loan.create'), ['class' => 'btn btn-success']) }}
                {{ link_to_route('loans.index', __('app.cancel'), [], ['class' => 'btn btn-secondary']) }}
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

@section('styles')
    {{ Html::style(url('css/plugins/jquery.datetimepicker.css')) }}
@endsection

@push('scripts')
    {{ Html::script(url('js/plugins/jquery.datetimepicker.js')) }}
<script>
(function () {
    $('.date-select').datetimepicker({
        timepicker:false,
        format:'Y-m-d',
        closeOnDateSelect: true,
        scrollInput: false,
        dayOfWeekStart: 1
    });
})();
</script>
@endpush

resources/views/loans/edit.blade.php
@extends('layouts.app')

@section('title', __('loan.edit'))

@section('content')
<div class="row">
    <div class="col-md-6 offset-md-3">
        @if (request('action') == 'delete' && $loan)
        @can('delete', $loan)
            <div class="card">
                <div class="card-header"><h3 class="card-title">{{ __('loan.delete') }}</h3></div>
                <div class="card-body">
                    <table class="table table-sm table-responsive-sm table-hover mb-0">
                        <tbody>
                            <tr><td>{{ __('loan.partner') }}</td><td>{{ $loan->partner->name }}</td></tr>
                            <tr><td>{{ __('loan.type') }}</td><td>{{ $loan->type }}</td></tr>
                            <tr><td>{{ __('loan.amount') }}</td><td class="text-right">{{ $loan->amount_string }}</td></tr>
                            <tr><td>{{ __('loan.planned_payment_count') }}</td><td class="text-right">{{ $loan->planned_payment_count }}</td></tr>
                            <tr><td>{{ __('loan.payment_total') }}</td><td class="text-right">{{ $loan->payment_total_string }}</td></tr>
                            <tr><td>{{ __('loan.payment_remaining') }}</td><td class="text-right">{{ $loan->payment_remaining_string }}</td></tr>
                            <tr><td>{{ __('loan.description') }}</td><td>{{ $loan->description }}</td></tr>
                            <tr><td>{{ __('loan.start_date') }}</td><td>{{ $loan->start_date }}</td></tr>
                            <tr><td>{{ __('loan.end_date') }}</td><td>{{ $loan->end_date }}</td></tr>
                        </tbody>
                    </table>
                </div>
                <hr style="margin:0">
                <div class="card-body text-danger">{{ __('loan.delete_confirm') }}</div>
                <div class="card-footer">
                    {!! FormField::delete(
                        ['route' => ['loans.destroy', $loan]],
                        __('app.delete_confirm_button'),
                        ['class' => 'btn btn-danger'],
                        ['loan_id' => $loan->id]
                    ) !!}
                    {{ link_to_route('loans.edit', __('app.cancel'), [$loan], ['class' => 'btn btn-secondary']) }}
                </div>
            </div>
        @endcan
        @else
        <div class="card">
            <div class="card-header"><h3 class="card-title">{{ __('loan.edit') }}</h3></div>
            {{ Form::model($loan, ['route' => ['loans.update', $loan], 'method' => 'patch']) }}
            <div class="card-body">
                {!! FormField::select('partner_id', $partners, ['required' => true, 'label' => __('loan.partner')]) !!}
                {!! FormField::radios('type_id', $loanTypes, ['required' => true, 'label' => __('loan.type')]) !!}
                <div class="row">
                    <div class="col-md-6">
                        {!! FormField::text('amount', ['required' => true, 'type' => 'number', 'label' => __('loan.amount')]) !!}
                    </div>
                    <div class="col-md-6">
                        {!! FormField::text('planned_payment_count', ['required' => true, 'type' => 'number', 'value' => old('planned_payment_count', $loan->planned_payment_count), 'label' => __('loan.planned_payment_count')]) !!}
                    </div>
                </div>
                {!! FormField::textarea('description', ['label' => __('loan.description')]) !!}
                <div class="row">
                    <div class="col-md-6">
                        {!! FormField::text('start_date', ['class' => 'date-select', 'label' => __('loan.start_date')]) !!}
                    </div>
                    <div class="col-md-6">
                        {!! FormField::text('end_date', ['class' => 'date-select', 'label' => __('loan.end_date')]) !!}
                    </div>
                </div>
            </div>
            <div class="card-footer">
                {{ Form::submit(__('loan.update'), ['class' => 'btn btn-success']) }}
                {{ link_to_route('loans.show', __('app.cancel'), [$loan], ['class' => 'btn btn-secondary']) }}
                @can('delete', $loan)
                    {{ link_to_route('loans.edit', __('app.delete'), [$loan, 'action' => 'delete'], ['class' => 'btn btn-danger float-right', 'id' => 'del-loan-'.$loan->id]) }}
                @endcan
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endif
@endsection

@section('styles')
    {{ Html::style(url('css/plugins/jquery.datetimepicker.css')) }}
@endsection

@push('scripts')
    {{ Html::script(url('js/plugins/jquery.datetimepicker.js')) }}
<script>
(function () {
    $('.date-select').datetimepicker({
        timepicker:false,
        format:'Y-m-d',
        closeOnDateSelect: true,
        scrollInput: false,
        dayOfWeekStart: 1
    });
})();
</script>
@endpush

resources/views/loans/index.blade.php
@extends('layouts.app')

@section('title', __('loan.list'))

@section('content')
<div class="page-header">
    <h1 class="page-title">{{ __('loan.list') }}</h1>
    <div class="page-subtitle">{{ __('app.total') }} : {{ $loans->total() }} {{ __('loan.loan') }}</div>
    <div class="page-options d-flex">
        {{ link_to_route('loans.create', __('loan.create'), [], ['class' => 'btn btn-success']) }}
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card table-responsive">
            <div class="card-header d-block d-sm-flex">
                {{ Form::open(['method' => 'get', 'class' => 'form-inline']) }}
                {!! FormField::text('q', ['label' => __('loan.search'), 'placeholder' => __('loan.search_text'), 'class' => 'form-control-sm mx-sm-2']) !!}
                {{ Form::hidden('type_id', request('type_id')) }}
                <div class="form-group">
                    {{ Form::submit(__('loan.search'), ['class' => 'btn btn-info btn-sm mr-2']) }}
                    {{ link_to_route('loans.index', __('app.reset'), request(['type_id']), ['class' => 'btn btn-secondary btn-sm mr-2']) }}
                </div>
                {{ Form::close() }}
                <div class="card-options">
                    <div class="btn-group">
                        {{ link_to_route('loans.index', __('loan.all'), ['type_id' => null] + request(['q']), ['class' => 'btn btn-sm '.(request('type_id') == null ? 'btn-info active' : 'btn-secondary')]) }}
                        {{ link_to_route('loans.index', __('loan.types.debt'), ['type_id' => 1] + request(['q']), ['class' => 'btn btn-sm '.(request('type_id') == '1' ? 'btn-info active' : 'btn-secondary')]) }}
                        {{ link_to_route('loans.index', __('loan.types.receivable'), ['type_id' => 2] + request(['q']), ['class' => 'btn btn-sm '.(request('type_id') === '2' ? 'btn-info active' : 'btn-secondary')]) }}
                    </div>
                </div>
            </div>
            <table class="table table-sm table-responsive-sm table-hover table-hover mb-0">
                <thead>
                    <tr>
                        <th class="text-center">{{ __('app.table_no') }}</th>
                        <th>{{ __('loan.partner') }}</th>
                        <th>{{ __('loan.type') }}</th>
                        <th class="text-right">{{ __('loan.amount') }}</th>
                        <th>{{ __('app.description') }}</th>
                        <th class="text-center">{{ __('loan.start_date') }}</th>
                        <th class="text-center">{{ __('loan.end_date') }}</th>
                        <th class="text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($loans as $key => $loan)
                    <tr>
                        <td class="text-center">{{ $loans->firstItem() + $key }}</td>
                        <td>{{ $loan->partner->name }}</td>
                        <td>{{ $loan->type }}</td>
                        <td class="text-right">{{ $loan->amount_string }}</td>
                        <td>{{ $loan->description }}</td>
                        <td class="text-center">{{ $loan->start_date }}</td>
                        <td class="text-center">{{ $loan->end_date }}</td>
                        <td class="text-center">
                            @can('view', $loan)
                                {{ link_to_route(
                                    'loans.show',
                                    __('app.show'),
                                    [$loan],
                                    ['class' => 'btn btn-secondary btn-sm', 'id' => 'show-loan-' . $loan->id]
                                ) }}
                            @endcan
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="card-body">{{ $loans->appends(Request::except('page'))->render() }}</div>
        </div>
    </div>
</div>
@endsection

resources/views/loans/show.blade.php
@extends('layouts.app')

@section('title', __('loan.detail'))

@section('content')
<div class="row">
    <div class="col-md-5">
        <div class="card">
            <div class="card-header"><h3 class="card-title">{{ __('loan.detail') }}</h3></div>
            <table class="table table-sm table-responsive-sm table-hover card-table">
                <tbody>
                    <tr><td>{{ __('loan.partner') }}</td><td>{{ $loan->partner->name }}</td></tr>
                    <tr><td>{{ __('loan.type') }}</td><td>{{ $loan->type }}</td></tr>
                    <tr><td>{{ __('loan.amount') }}</td><td class="text-right">{{ $loan->amount_string }}</td></tr>
                    <tr><td>{{ __('loan.planned_payment_count') }}</td><td class="text-right">{{ $loan->planned_payment_count }}</td></tr>
                    <tr><td>{{ __('loan.payment_total') }}</td><td class="text-right">{{ $loan->payment_total_string }}</td></tr>
                    <tr><td>{{ __('loan.payment_remaining') }}</td><td class="text-right">{{ $loan->payment_remaining_string }}</td></tr>
                    <tr><td>{{ __('loan.description') }}</td><td>{{ $loan->description }}</td></tr>
                    <tr><td>{{ __('loan.start_date') }}</td><td>{{ $loan->start_date }}</td></tr>
                    <tr><td>{{ __('loan.end_date') }}</td><td>{{ $loan->end_date }}</td></tr>
                </tbody>
            </table>
            <div class="card-footer">
                @can('update', $loan)
                    {{ link_to_route('loans.edit', __('loan.edit'), [$loan], ['class' => 'btn btn-warning', 'id' => 'edit-loan-'.$loan->id]) }}
                @endcan
                {{ link_to_route('loans.index', __('loan.back_to_index'), [], ['class' => 'btn btn-secondary']) }}
            </div>
        </div>
    </div>
    <div class="col-md-7">
        <div class="page-header">
            <h1 class="page-title">{{ __('transaction.list') }}</h1>
            <div class="page-options d-flex">
                @can('update', $loan)
                    @if(Request::get('action') != 'add_transaction')
                        {{ link_to_route(
                            'loans.show',
                            __('loan.add_transaction'),
                            [$loan, 'action' => 'add_transaction'],
                            ['class' => 'btn btn-success', 'id' => 'add_transaction-'.$loan->id]
                        ) }}
                    @endif
                @endcan
            </div>
        </div>

        @can('update', $loan)
            @if(Request::has('action'))
                @include('loans.partials.single_actions')
            @endif
        @endcan

        <div class="card table-responsive">
            <table class="table table-sm table-responsive-sm table-hover table-bordered mb-0">
                <thead>
                    <tr>
                        <th class="text-center">{{ __('app.table_no') }}</th>
                        <th class="text-center">{{ __('app.date') }}</th>
                        <th>{{ __('transaction.description') }}</th>
                        <th class="text-right">{{ __('transaction.amount') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($transactions as $key => $transaction)
                    <tr>
                        <td class="text-center">{{ 1 + $key }}</td>
                        <td class="text-center text-middle">{{ $transaction->date }}</td>
                        <td>{{ $transaction->description }}</td>
                        <td class="text-right">{{ $transaction->amount_string }}</td>
                    </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="3">{{ __('app.total') }}</th>
                        <th class="text-right">
                            @php
                                $transactionSum = $transactions->sum(function ($transaction) {
                                    return $transaction->in_out ? $transaction->amount : -$transaction->amount;
                                });
                            @endphp
                            {{ number_format($transactionSum, 2) }}
                        </th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection

@section('styles')
    {{ Html::style(url('css/plugins/jquery.datetimepicker.css')) }}
@endsection

@push('scripts')
    {{ Html::script(url('js/plugins/jquery.datetimepicker.js')) }}
<script>
(function () {
    $('#transactionModal').modal({
        show: true,
        backdrop: 'static',
    });
    $('.date-select').datetimepicker({
        timepicker:false,
        format:'Y-m-d',
        closeOnDateSelect: true,
        scrollInput: false,
        dayOfWeekStart: 1
    });
})();
</script>
@endpush