routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome')->name('welcome')->middleware('guest');

Auth::routes();

// Change Password Routes
Route::get('change-password', 'Auth\ChangePasswordController@show');
Route::patch('change-password', 'Auth\ChangePasswordController@update')->name('password.change');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'TransactionsController@index')->name('home');

    /*
     * User Profile Routes
     */
    Route::get('profile', 'Auth\ProfileController@show')->name('profile.show');
    Route::get('profile/edit', 'Auth\ProfileController@edit')->name('profile.edit');
    Route::patch('profile/update', 'Auth\ProfileController@update')->name('profile.update');

    /*
     * Transactions Routes
     */
    Route::get('transaction_search', 'TransactionSearchController@index')->name('transaction_search.index');
    Route::get('transactions/export-csv', 'Transactions\ExportController@csv')->name('transactions.exports.csv');
    Route::resource('transactions', 'TransactionsController');

    /*
     * Categories Routes
     */
    Route::get('categories/{category}/export-csv', 'Transactions\ExportController@byCategory')->name('transactions.exports.by_category');
    Route::resource('categories', 'CategoriesController');

    /*
     * Loans Routes
     */
    Route::resource('loans', 'LoanController');
    Route::post('loans/{loan}/transactions', 'Loans\TransactionController@store')
        ->name('loans.transactions.store');

    /*
     * Report Routes
     */
    Route::get('/report', 'ReportsController@index')->name('reports.index');

    /*
     * Partners Routes
     */
    Route::get('partners/{partner}/export-csv', 'Transactions\ExportController@byPartner')->name('transactions.exports.by_partner');
    Route::resource('partners', 'PartnerController');

    /*
     * Lang switcher routes
     */
    Route::patch('lang_switch', 'LangSwitcherController@update')->name('lang.switch');
});

resources/views/layouts/partials/lang_switcher.blade.php
@foreach (['en', 'id'] as $langKey)
{!! FormField::formButton(
    [
        'method' => 'patch',
        'route' => 'lang.switch',
        'title' => __('app.switch_'.$langKey.'_lang')
    ],
    $langKey,
    [
        'class' => 'btn btn-sm '.(config('app.locale') == $langKey ? 'btn-info' : 'btn-secondary'),
        'id' => 'lang_'.$langKey
    ] + (config('app.locale') == $langKey ? ['disabled' => 'disabled'] : []),
    ['lang' => $langKey]
) !!}
@endforeach

resources/views/layouts/partials/noty.blade.php
@if(Session::has('flash_notification.message'))
@php
    $level = Session::get('flash_notification.level');
    if ($level == 'info') {
        $level = 'information';
    }
@endphp
<script src="{{ asset('js/plugins/noty.js') }}"></script>
<script>
    noty({
        type: '{{ $level }}',
        layout: 'bottomRight',
        text: '{{ Session::get('flash_notification.message') }}',
        timeout: 3000
    });
</script>
@endif

resources/views/layouts/partials/top_nav.blade.php
<nav class="navbar navbar-expand-sm navbar-light bg-white shadow-sm">
    <div class="container">
        <div class="navbar-header">
            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ route('home') }}">
                @guest
                    {{ config('app.name', 'Laravel') }}
                @else
                    {{ auth()->user()->name }}
                @endguest
            </a>
        </div>
        <div class="nav navbar-nav mx-2 flex-row">
            @auth
            <a href="{{ route('home') }}" class="xs-navbar mr-4" title="{{ __('transaction.current_balance') }}">
                <img src="{{ asset('images/icons8-coins-16.png') }}" alt=""> {{ format_number(balance(date('Y-m-d'))) }}
            </a>
            @include ('layouts.partials.lang_switcher')
            @endauth
        </div>

        <!-- Right Side Of Navbar -->
        <div class="nav navbar-nav ml-auto d-none d-sm-block">
            <!-- Authentication Links -->
            <a class="xs-navbar mr-4" href="{{ route('transactions.index') }}" title="{{ __('transaction.transaction') }}">
                <i class="fe fe-repeat h3 d-inline d-lg-none"></i>
                <span class="d-none d-lg-inline"><i class="fe fe-repeat"></i> {{ __('transaction.transaction') }}</span>
            </a>
            <a class="xs-navbar mr-4" href="{{ route('loans.index') }}" title="{{ __('loan.loan') }}">
                <i class="fe fe-refresh-cw h3 d-inline d-lg-none"></i>
                <span class="d-none d-lg-inline"><i class="fe fe-refresh-cw"></i> {{ __('loan.loan') }}</span>
            </a>
            <a class="xs-navbar mr-4" href="{{ route('reports.index') }}" title="{{ __('report.report') }}">
                <i class="fe fe-bar-chart-2 h3 d-inline d-lg-none"></i>
                <span class="d-none d-lg-inline"><i class="fe fe-bar-chart-2"></i> {{ __('report.report') }}</span>
            </a>
            <a class="xs-navbar mr-4" href="{{ route('profile.show') }}" title="{{ __('settings.settings') }}">
                <i class="fe fe-settings h3 d-inline d-lg-none"></i>
                <span class="d-none d-lg-inline"><i class="fe fe-settings"></i> {{ __('settings.settings') }}</span>
            </a>
            <a class="xs-navbar mr-4" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                         document.getElementById('logout-form').submit();">
                 <i class="fe fe-log-out h3 d-inline d-lg-none"></i>
                <i class="fe fe-log-out d-none d-lg-inline"></i>
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                <input type="submit" value="{{ __('auth.logout') }}" style="display: none;">
                {{ csrf_field() }}
            </form>
        </div>
    </div>
</nav>

<!-- Mobile Navigation -->
<nav class="navbar fixed-bottom navbar-light bg-white d-block d-sm-none border-top">
    <div class="row text-center small justify-content-center">
        <a class="col border-right border-primary" href="{{ route('transactions.index') }}" title="{{ __('transaction.transaction') }}">
            <div><i class="fe fe-repeat h3"></i></div>
            {{ __('transaction.transaction') }}
        </a>
        <a class="col border-right border-primary" href="{{ route('loans.index') }}" title="{{ __('loan.loan') }}">
            <div><i class="fe fe-refresh-cw h3"></i></div>
            {{ __('loan.loan') }}
        </a>
        <a class="col border-right border-primary" href="{{ route('reports.index') }}" title="{{ __('report.report') }}">
            <div><i class="fe fe-bar-chart-2 h3"></i></div>
            {{ __('report.report') }}
        </a>
        <a class="col" href="{{ route('profile.show') }}" title="{{ __('settings.settings') }}">
            <div><i class="fe fe-settings h3"></i></div>
            {{ __('settings.settings') }}
        </a>
    </div>
</nav>