routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome')->name('welcome')->middleware('guest');

Auth::routes();

// Change Password Routes
Route::get('change-password', 'Auth\ChangePasswordController@show');
Route::patch('change-password', 'Auth\ChangePasswordController@update')->name('password.change');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'TransactionsController@index')->name('home');

    /*
     * User Profile Routes
     */
    Route::get('profile', 'Auth\ProfileController@show')->name('profile.show');
    Route::get('profile/edit', 'Auth\ProfileController@edit')->name('profile.edit');
    Route::patch('profile/update', 'Auth\ProfileController@update')->name('profile.update');

    /*
     * Transactions Routes
     */
    Route::get('transaction_search', 'TransactionSearchController@index')->name('transaction_search.index');
    Route::get('transactions/export-csv', 'Transactions\ExportController@csv')->name('transactions.exports.csv');
    Route::resource('transactions', 'TransactionsController');

    /*
     * Categories Routes
     */
    Route::get('categories/{category}/export-csv', 'Transactions\ExportController@byCategory')->name('transactions.exports.by_category');
    Route::resource('categories', 'CategoriesController');

    /*
     * Loans Routes
     */
    Route::resource('loans', 'LoanController');
    Route::post('loans/{loan}/transactions', 'Loans\TransactionController@store')
        ->name('loans.transactions.store');

    /*
     * Report Routes
     */
    Route::get('/report', 'ReportsController@index')->name('reports.index');

    /*
     * Partners Routes
     */
    Route::get('partners/{partner}/export-csv', 'Transactions\ExportController@byPartner')->name('transactions.exports.by_partner');
    Route::resource('partners', 'PartnerController');

    /*
     * Lang switcher routes
     */
    Route::patch('lang_switch', 'LangSwitcherController@update')->name('lang.switch');
});

app/Category.php
<?php

namespace App;

use App\Traits\Models\ConstantsGetter;
use App\Traits\Models\ForUser;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use ForUser, ConstantsGetter;

    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 1;

    protected $appends = ['status'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'description', 'color', 'status_id', 'creator_id'];

    /**
     * Category belongs to user creator relation.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function creator()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Category has many transactions relation.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }

    /**
     * Get category name label attribute.
     *
     * @return string
     */
    public function getNameLabelAttribute()
    {
        return '<span class="badge" style="background-color: '.$this->color.'">'.$this->name.'</span>';
    }

    public function getStatusAttribute()
    {
        return $this->status_id == static::STATUS_INACTIVE ? __('app.inactive') : __('app.active');
    }
}

app/Loan.php
<?php

namespace App;

use App\Traits\Models\ForUser;
use Illuminate\Database\Eloquent\Model;

class Loan extends Model
{
    use ForUser;

    const TYPE_DEBT = 1;
    const TYPE_RECEIVABLE = 2;

    protected $fillable = [
        'partner_id', 'type_id', 'amount', 'description', 'creator_id',
        'start_date', 'end_date', 'planned_payment_count',
    ];

    public function creator()
    {
        return $this->belongsTo(User::class);
    }

    public function partner()
    {
        return $this->belongsTo(Partner::class);
    }

    public function getTypeAttribute()
    {
        if ($this->type_id == Loan::TYPE_DEBT) {
            return __('loan.types.debt');
        }

        return __('loan.types.receivable');
    }

    public function getAmountStringAttribute()
    {
        return number_format($this->amount, 2);
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }

    public function getPaymentTotalAttribute()
    {
        $paymentType = $this->type_id == static::TYPE_DEBT ? 0 : 1;

        return $this->transactions()->where('in_out', $paymentType)->sum('amount');
    }

    public function getPaymentTotalStringAttribute()
    {
        return number_format($this->payment_total, 2);
    }

    public function getPaymentRemainingAttribute()
    {
        return $this->amount - $this->payment_total;
    }

    public function getPaymentRemainingStringAttribute()
    {
        return number_format($this->payment_remaining, 2);
    }

    public function getTypeLabelAttribute()
    {
        $bgColor = $this->type_id == static::TYPE_DEBT ? '#00aabb' : '#bb004f';
        $type = $this->type;
        if ($this->end_date) {
            $type .= ' <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>';
        }

        return '<span class="badge" style="background-color: '.$bgColor.'">'.$type.'</span>';
    }

    public function delete()
    {
        $this->transactions()->update(['loan_id' => null]);

        return parent::delete();
    }
}

app/Http/Controllers/Api/CategoriesController.php
<?php

namespace App\Http\Controllers\Api;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\Categories\CreateRequest;
use App\Http\Requests\Categories\DeleteRequest;
use App\Http\Requests\Categories\UpdateRequest;

class CategoriesController extends Controller
{
    /**
     * Get a listing of the category.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();

        return $categories;
    }

    /**
     * Store a newly created category in storage.
     *
     * @param  \App\Http\Requests\Categories\CreateRequest  $categoryCreateForm
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $categoryCreateForm)
    {
        $category = $categoryCreateForm->save();

        return response()->json([
            'message' => __('category.created'),
            'data' => $category,
        ], 201);
    }

    /**
     * Update the specified category in storage.
     *
     * @param  \App\Http\Requests\Categories\UpdateRequest  $categoryUpdateForm
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $categoryUpdateForm, Category $category)
    {
        $category = $categoryUpdateForm->save();

        return response()->json([
            'message' => __('category.updated'),
            'data' => $category,
        ]);
    }

    /**
     * Remove the specified category from storage.
     *
     * @param  \App\Http\Requests\Categories\DeleteRequest  $categoryDeleteForm
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(DeleteRequest $categoryDeleteForm, Category $category)
    {
        if ($categoryDeleteForm->delete()) {
            return response()->json(['message' => __('category.deleted')]);
        }

        return response()->json('Unprocessable Entity.', 422);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\Categories\CreateRequest;
use App\Http\Requests\Categories\DeleteRequest;
use App\Http\Requests\Categories\UpdateRequest;
use App\Transaction;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the category.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function index()
    {
        $editableCategory = null;
        $categories = Category::orderBy('name')->get();

        if (in_array(request('action'), ['edit', 'delete']) && request('id') != null) {
            $editableCategory = Category::find(request('id'));
        }

        return view('categories.index', compact('categories', 'editableCategory'));
    }

    /**
     * Store a newly created category in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $categoryCreateForm)
    {
        $category = $categoryCreateForm->save();

        flash(__('category.created'), 'success');

        return redirect()->route('categories.index');
    }

    /**
     * Show transaction listing of a category.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\View\View
     */
    public function show(Category $category)
    {
        $categories = [];
        $editableTransaction = null;
        $year = request('year', date('Y'));
        $partners = $this->getPartnerList()->prepend('-- '.__('transaction.no_partner').' --', 'null');

        $defaultStartDate = auth()->user()->account_start_date ?: date('Y-m').'-01';
        $startDate = request('start_date', $defaultStartDate);
        $endDate = request('end_date', date('Y-m-d'));

        $transactions = $this->getCategoryTransactions($category, [
            'partner_id' => request('partner_id'),
            'start_date' => $startDate,
            'end_date' => $endDate,
            'query' => request('query'),
        ]);
        $incomeTotal = $this->getIncomeTotal($transactions);
        $spendingTotal = $this->getSpendingTotal($transactions);

        if (in_array(request('action'), ['edit', 'delete']) && request('id') != null) {
            $categories = $this->getCategoryList();
            $editableTransaction = Transaction::find(request('id'));
        }

        return view('categories.show', compact(
            'category', 'transactions', 'year', 'incomeTotal', 'spendingTotal',
            'startDate', 'endDate', 'partners', 'editableTransaction', 'categories'
        ));
    }

    /**
     * Update the specified category in storage.
     *
     * @param  \App\Http\Requests\Categories\UpdateRequest  $categoryUpdateForm
     * @param  \App\Category  $category
     * @return \Illuminate\Routing\Redirector
     */
    public function update(UpdateRequest $categoryUpdateForm, Category $category)
    {
        $category = $categoryUpdateForm->save();

        flash(__('category.updated'), 'success');

        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified category from storage.
     *
     * @param  \App\Http\Requests\Categories\DeleteRequest  $categoryDeleteForm
     * @param  \App\Category  $category
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy(DeleteRequest $categoryDeleteForm, Category $category)
    {
        if ($categoryDeleteForm->delete()) {
            flash(__('category.deleted'), 'warning');

            return redirect()->route('categories.index');
        }

        flash(__('category.undeleted'), 'warning');

        return back();
    }
}

resources/views/categories/forms.blade.php
@if (request('action') == 'create')
@can('create', new App\Category)
    <div id="categoryModal" class="modal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ __('category.create') }}</h5>
                    {{ link_to_route('categories.index', '', [], ['class' => 'close']) }}
                </div>
                {!! Form::open(['route' => 'categories.store']) !!}
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            {!! FormField::text('name', ['required' => true, 'label' => __('category.name')]) !!}
                        </div>
                        <div class="col-md-6">
                            <div class="form-group required">
                                <label for="color" class="control-label">{{ __('category.color') }}</label>
                                <div id="color" class="input-group colorpicker-component">
                                    <input name="color" type="text" value="#00AABB" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    {!! FormField::textarea('description', ['label' => __('category.description')]) !!}
                </div>
                <div class="modal-footer">
                    {!! Form::submit(__('category.create'), ['class' => 'btn btn-success']) !!}
                    {{ link_to_route('categories.index', __('app.cancel'), [], ['class' => 'btn btn-secondary']) }}
                </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
@endcan
@endif

@if (request('action') == 'edit' && $editableCategory)
@can('update', $editableCategory)
    <div id="categoryModal" class="modal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ __('category.edit') }}</h5>
                    {{ link_to_route('categories.index', '', [], ['class' => 'close']) }}
                </div>
                {!! Form::model($editableCategory, ['route' => ['categories.update', $editableCategory], 'method' => 'patch']) !!}
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            {!! FormField::text('name', ['required' => true, 'label' => __('category.name')]) !!}
                        </div>
                        <div class="col-md-6">
                            <div class="form-group required">
                                <label for="color" class="control-label">{{ __('category.color') }}</label>
                                <div id="color" class="input-group colorpicker-component">
                                    <input name="color" type="text" value="{{ $editableCategory->color }}" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    {!! FormField::textarea('description', ['label' => __('category.description')]) !!}
                    {!! FormField::radios('status_id', [App\Category::STATUS_INACTIVE => __('app.inactive'), App\Category::STATUS_ACTIVE => __('app.active')], ['label' => __('app.status')]) !!}
                </div>
                <div class="modal-footer">
                    {!! Form::submit(__('category.update'), ['class' => 'btn btn-success']) !!}
                    {{ link_to_route('categories.index', __('app.cancel'), [], ['class' => 'btn btn-secondary']) }}
                    @can('delete', $editableCategory)
                        {!! link_to_route(
                            'categories.index',
                            __('app.delete'),
                            ['action' => 'delete', 'id' => $editableCategory->id],
                            ['id' => 'del-category-'.$editableCategory->id, 'class' => 'btn btn-danger float-left']
                        ) !!}
                    @endcan
                </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
@endcan
@endif

@if (request('action') == 'delete' && $editableCategory)
@can('delete', $editableCategory)
    <div id="categoryModal" class="modal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ __('category.delete') }} {{ $editableCategory->type }}</h5>
                    {{ link_to_route('categories.index', '', [], ['class' => 'close']) }}
                </div>
                {!! Form::open(['url' => route('categories.destroy', $editableCategory), 'method' => 'DELETE']) !!}
                <div class="modal-body">
                    <label class="control-label">{{ __('category.name') }}</label>
                    <p>{!! $editableCategory->name_label !!}</p>
                    <label class="control-label">{{ __('category.description') }}</label>
                    <p>{{ $editableCategory->description }}</p>
                    {!! $errors->first('category_id', '<span class="form-error small">:message</span>') !!}
                </div>
                <hr style="margin:0">
                <div class="modal-body">
                    {!! Form::hidden('category_id', $editableCategory->id) !!}
                    {!! Form::checkbox('delete_transactions', 1, false, ['id' => 'delete_transactions']) !!}
                    {!! Form::label('delete_transactions', __('category.delete_transactions')) !!}
                    <br>
                    {{ __('app.delete_confirm') }}
                </div>
                <div class="modal-footer">
                    {!! Form::submit(__('app.delete_confirm_button'), ['class' => 'btn btn-danger']) !!}
                    {{ link_to_route('categories.index', __('app.cancel'), [], ['class' => 'btn btn-secondary']) }}
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endcan
@endif

resources/views/categories/index.blade.php
@extends('layouts.settings')

@section('title', __('category.list'))

@section('content_settings')
<div class="page-header">
    <h1 class="page-title">{{ __('category.list') }}</h1>
    <div class="page-subtitle">{{ __('app.total') }} : {{ $categories->count() }} {{ __('category.category') }}</div>
    <div class="page-options d-flex">
        @can('create', new App\Category)
            {{ link_to_route('categories.index', __('category.create'), ['action' => 'create'], ['class' => 'btn btn-success']) }}
        @endcan
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card table-responsive">
            <table class="table table-sm table-responsive-sm table-hover mb-0">
                <thead>
                    <tr>
                        <th class="text-center">{{ __('app.table_no') }}</th>
                        <th class="text-nowrap">{{ __('category.name') }}</th>
                        <th class="text-center">{{ __('app.status') }}</th>
                        <th>{{ __('category.description') }}</th>
                        <th class="text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($categories as $key => $category)
                    <tr>
                        <td class="text-center">{{ 1 + $key }}</td>
                        <td class="text-nowrap">{!! $category->name_label !!}</td>
                        <td class="text-nowrap text-center">{{ $category->status }}</td>
                        <td>{{ $category->description }}</td>
                        <td class="text-center text-nowrap">
                            @can('view', $category)
                                {{ link_to_route(
                                    'categories.show',
                                    __('category.view_transactions'),
                                    $category,
                                    ['class' => 'btn btn-sm btn-secondary']
                                ) }}
                            @endcan
                            @can('update', $category)
                                {{ link_to_route(
                                    'categories.index',
                                    __('app.edit'),
                                    ['action' => 'edit', 'id' => $category->id],
                                    [
                                        'id' => 'edit-category-'.$category->id,
                                        'class' => 'btn btn-sm btn-warning',
                                    ]
                                ) }}
                            @endcan
                        </td>
                    </tr>
                    @empty
                    <tr><td colspan="4">{{ __('category.not_found') }}</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-md-4">
        @if(Request::has('action'))
        @include('categories.forms')
        @endif
    </div>
</div>
@endsection

@section('styles')
    {{ Html::style(url('css/plugins/bootstrap-colorpicker.min.css')) }}
@endsection

@push('scripts')
    {{ Html::script(url('js/plugins/bootstrap-colorpicker.min.js')) }}
<script>
(function () {
    $('#categoryModal').modal({
        show: true,
        backdrop: 'static',
    });
    $('#color').colorpicker();
})();
</script>
@endpush

resources/views/categories/show.blade.php
@extends('layouts.settings')

@section('title', __('category.transactions'))

@section('content_settings')

<div class="page-header">
    <h1 class="page-title">{{ $category->name }}</h1>
    <div class="page-subtitle">{{ __('category.transactions') }}</div>
    <div class="page-options d-flex">
        {{ link_to_route('categories.index', __('category.back_to_index'), [], ['class' => 'btn btn-secondary float-right']) }}
    </div>
</div>

@include('transactions.partials.stats')

@if ($category->description)
    <div class="alert alert-info"><strong>{{ __('app.description') }}:</strong><br>{{ $category->description }}</div>
@endif

<div class="row">
    <div class="col-md-12">
        <div class="card table-responsive">
            <div class="card-header">
                @include('categories.partials.show_filter')
            </div>
            @desktop
            <table class="table table-sm table-responsive-sm table-hover table-bordered mb-0">
                <thead>
                    <tr>
                        <th class="text-center col-md-1">{{ __('app.table_no') }}</th>
                        <th class="text-center col-md-2">{{ __('app.date') }}</th>
                        <th class="col-md-7">{{ __('transaction.description') }}</th>
                        <th class="text-right col-md-2">{{ __('transaction.amount') }}</th>
                        <th class="text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($transactions as $key => $transaction)
                    <tr>
                        <td class="text-center">{{ 1 + $key }}</td>
                        <td class="text-center">{{ $transaction->date }}</td>
                        <td>
                            {{ $transaction->description }}
                            <span class="float-right">
                                {!!optional($transaction->partner)->name_label !!}
                                {!!optional($transaction->loan)->type_label !!}
                            </span>
                        </td>
                        <td class="text-right">{{ $transaction->amount_string }}</td>
                        <td class="text-center">
                            @can('update', $transaction)
                                {!! link_to_route(
                                    'categories.show',
                                    __('app.edit'),
                                    [$category->id, 'action' => 'edit', 'id' => $transaction->id] + request(['start_date', 'end_date', 'query', 'partner_id']),
                                    ['id' => 'edit-transaction-'.$transaction->id]
                                ) !!}
                            @endcan
                        </td>
                    </tr>
                    @empty
                    <tr><td colspan="5">{{ __('transaction.not_found') }}</td></tr>
                    @endforelse
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="3" class="text-right">{{ __('app.total') }}</th>
                        <th class="text-right">
                            {{ format_number($transactions->sum(function ($transaction) {
                                return $transaction->in_out ? $transaction->amount : -$transaction->amount;
                            })) }}
                        </th>
                        <th>&nbsp;</th>
                    </tr>
                </tfoot>
            </table>
            @elsedesktop
            <div class="card-body">
                @foreach ($transactions as $transaction)
                    @include('categories.partials.single_transaction_mobile', ['transaction' => $transaction])
                @endforeach
            </div>
            @enddesktop
        </div>
    </div>
</div>
@if(Request::has('action'))
@include('categories.partials.transaction-forms')
@endif
@endsection

@section('styles')
    {{ Html::style(url('css/plugins/bootstrap-colorpicker.min.css')) }}
    {{ Html::style(url('css/plugins/jquery.datetimepicker.css')) }}
@endsection

@push('scripts')
    {{ Html::script(url('js/plugins/bootstrap-colorpicker.min.js')) }}
    {{ Html::script(url('js/plugins/jquery.datetimepicker.js')) }}
<script>
(function () {
    $('#transactionModal').modal({
        show: true,
        backdrop: 'static',
    });
    $('.date-select').datetimepicker({
        timepicker:false,
        format:'Y-m-d',
        closeOnDateSelect: true,
        scrollInput: false,
        dayOfWeekStart: 1
    });
})();
</script>
@endpush